spring:
  datasource:
    username: root
    password: toor
    url: jdbc:mysql://localhost:3306/filecreator
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop

